### ISSUE TITLE
FR: skip code blocks and :tag: when parsing

### ISSUE THREAD

**Issue by lef-est** [sawhney17/logseq-automatic-linker#13]
Thanks for the addition of "auto-parse on enter". It's become the most frictionless way of linking in logseq. It'll be great if it can recognize code (both code blocks & inline code, markdown or org) and :tag: (org) and skip putting [[]] in them :)

**Comment by Laptop765** [comment]
It also seems that a page whose name contains things that would be parsed as pages ends up automatically linking as well.

Given pages `This is a test` and `Test`:

Typing `[[This is a test]] of the plugin` and auto-linking ends up generating `[[This is a [[test]]]]`

**Comment by Perlsowisdom** [comment]
Since a #tag is functionally a page, this issue also applies to text auto linking tags within pages. It'd be nice if you could give [[bracketed pages]] a priority over #tagged pages to try to fix this issue.

Given pages `This is a test page` and `#test`:

Typing  `[[This is a test page]]` generates `[[This is a #test page]]` when auto-linking.

**Comment by sawhney17** [comment]
code blocks and tags inside of brackets should no longer be parsed in 1.1.2
